runtime: python39

entrypoint: gunicorn main:app -k uvicorn.workers.UvicornWorker

env_variables:
  API_HOST: "https://clean-code-app-1744825963.uc.r.appspot.com"
  # MongoDB connection is now retrieved from Secret Manager
  MONGODB_NAME: "sloane_ai_service"
  TWILIO_ACCOUNT_SID: "AC8cc057f196bec4492fd4a6e8da90aa8a"
  # Auth token moved to Secret Manager
  TWILIO_PHONE_NUMBER: "+14245295093"
  # Flag to indicate we're running in production and should use Secret Manager
  USE_SECRET_MANAGER: "true"
  # Google Maps API key is now retrieved from Secret Manager

automatic_scaling:
  max_instances: 3