runtime: python311
service: default
instance_class: F1

env_variables:
  PROJECT_ID: "clean-code-app-1744825963"
  USE_SECRET_MANAGER: "true"
  GOOGLE_CLOUD_PROJECT: "clean-code-app-1744825963"

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto
  secure: always