runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  API_HOST: "https://clean-code-app-1744825963.uc.r.appspot.com"
  MONGODB_NAME: "sloane_ai_service" 
  TWILIO_ACCOUNT_SID: "AC8cc057f196bec4492fd4a6e8da90aa8a"
  TWILIO_PHONE_NUMBER: "+14245295093"
  USE_SECRET_MANAGER: "true"
  GOOGLE_CLOUD_PROJECT: "clean-code-app-1744825963"

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 3
  min_idle_instances: 1
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50