runtime: python39

entrypoint: gunicorn main:app -k uvicorn.workers.UvicornWorker

env_variables:
  API_HOST: "https://clean-code-app-1744825963.uc.r.appspot.com"
  MONGODB_NAME: "sloane_ai_service"
  TWILIO_ACCOUNT_SID: "AC8cc057f196bec4492fd4a6e8da90aa8a"
  TWILIO_PHONE_NUMBER: "+14245295093"
  # Force use of env vars temporarily until deployment issues resolved
  USE_SECRET_MANAGER: "false"
  GOOGLE_MAPS_API_KEY: "AIzaSyAVQNhMwjrnWGmwFZTQvVMBHgdB_IGdZt4"

automatic_scaling:
  max_instances: 3

