[build]
  base = "sloane-frontend-package"
  publish = "build"
  command = "./netlify-build.sh"

[build.environment]
  NODE_VERSION = "16"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  CI = "false"
  # Note: We're removing REACT_APP_API_URL so the app uses relative URLs
  # IMPORTANT: API keys should be set in Netlify environment variables, not here

[[redirects]]
  from = "/api/*"
  to = "https://fluted-mercury-455419-n0.uc.r.appspot.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200