# DO NOT USE THIS FILE
# This file is deprecated and should be ignored
# All configuration is now in the root netlify.toml file
# This file is kept for reference only and should not be used

# NETLIFY: PLEASE IGNORE THIS FILE