[build]
  command = "CI=false SKIP_PREFLIGHT_CHECK=true npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  CI = "false"
  # Do not define API keys here - they are set in Netlify dashboard

# API path redirects to the backend App Engine instance
[[redirects]]
  from = "/api/*"
  to = "https://clean-code-app-1744825963.uc.r.appspot.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"}

# Specific redirect for Google Business API endpoints
[[redirects]]
  from = "/business/*"
  to = "https://clean-code-app-1744825963.uc.r.appspot.com/api/business/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"} 

# Google Auth redirect
[[redirects]]
  from = "/auth/google"
  to = "https://clean-code-app-1744825963.uc.r.appspot.com/api/auth/google"
  status = 302
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200