# This file is deprecated - using root netlify.toml instead

[build.environment]
  NODE_VERSION = "16"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  CI = "false"
  # Note: We're removing REACT_APP_API_URL so the app uses relative URLs
  # API key should be set in the Netlify dashboard
  # REACT_APP_GOOGLE_MAPS_API_KEY = "YOUR_GOOGLE_MAPS_API_KEY_HERE"

[[redirects]]
  from = "/api/*"
  to = "https://clean-code-app-1744825963.uc.r.appspot.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200