[build]
  base = "/"
  publish = "build"
  command = "bash netlify/build.sh"

[build.environment]
  NODE_VERSION = "16"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  CI = "false"
  REACT_APP_API_URL = "https://fluted-mercury-455419-n0.uc.r.appspot.com/api"
  REACT_APP_GOOGLE_MAPS_API_KEY = "AIzaSyBai5EagIUmMY8Vaugzkc4obqydImC-fjA"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "https://fluted-mercury-455419-n0.uc.r.appspot.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}